# Run this when you stand outside frontend and backend folder
# VLG 
# ├──node
# └──mongodb
# docker-compose -f docker-compose.stack.yml --project-directory ./backend up
version: '3.1'
services:

  food-backend:
    container_name: vlfood_backend
    hostname: vlfood_backend
    image: registry.gitlab.com/b698/vanlanggo/vanlanggo-backend/vanlangfood:latest
    env_file:
      - .env
    tty: true
    ports:
      - 5000:5000
    # volumes:
    #   - ./files/:/usr/vlgo/gateway/files/:rw
    depends_on:
      - food-mongodb
    networks:
      - host
      - internalService
      - share_stack

  food-mongodb:
    container_name: vlfood_mongodb
    hostname: ${FOOD_MONGODB_HOST}
    image: mongo:4.4.6
    env_file:
      - .env
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${FOOD_MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${FOOD_MONGODB_PASSWORD}
    volumes:
      # - ./docker/db/vanlango-mongo-init.js:/docker-entrypoint-initdb.d/vanlango-mongo-init.js:ro
      - mongodb_data:/data/db:rw
    networks:
      - internalService
      - host


volumes:
  mongodb_data: 

networks:
  host:
    driver: bridge
  internalService:
    internal: true
  share_stack:
    external: true
